global:
  imageRegistry: "registry.stardream.link"
  imagePullSecrets:
  - stardreamkey
  storageClass: "local"
  redis:
    password: ""

master:
  persistence:
    size: 20Gi
  service:
    type: NodePort
    nodePorts:
      redis: 30004
    annotations:
      consul.register/enabled: "true"
      consul.register/service.name: "vpc.inf.redis"
      consul.register/service.health.tcp: "true"
      consul.register/service.health.port: "30003"
replica:
  persistence:
    size: 20Gi
